### ISSUE TITLE
Empty string search

### ISSUE THREAD

**Issue by EniotnaTennob** [lucasrochagit/nest-mongo-query-parser#5]
Hello @lucasrochagit 
Sorry if the question may seem stupid but how can I search on an empty string
![image](https://user-images.githubusercontent.com/38079195/192283137-ee6d91b6-5dab-4e2b-a136-4a6b68847cda.png)
thank you in advance

**Comment by EniotnaTennob** [comment]
maybe by changing this part of the code ?
![image](https://user-images.githubusercontent.com/38079195/192286126-edd0c6eb-94cf-4a57-9baa-7ada43e5c888.png)

**Comment by lucasrochagit** [comment]
Hi @EniotnaTennob!

Your question doesn't seem stupid, on the contrary, it's quite interesting.

I hadn't thought of this use case when I built the library. For this type of query works properly, I would need to consider an empty query value as valid.

There are many adjustments to be made to this library, but unfortunately I'm not having much time to maintain it.

For this case, so that values such as empty strings can be accepted, I need to change the following code snippet:

```ts
// src/lib/query/mongo.query.ts, line 165
function getSimpleFilterValue(
  filter: string
): string | number | boolean | Date | object | null {
  if (!filter) return null;
```
It should be:

```ts
// src/lib/query/mongo.query.ts, line 165
function getSimpleFilterValue(
  filter: string
): string | number | boolean | Date | object | null {
  if (filter === null || filter === undefined) return null;
```

Or:

```ts
// src/lib/query/mongo.query.ts, line 165
function getSimpleFilterValue(
  filter: string
): string | number | boolean | Date | object | null {
   if (filter === "" ) return filter;
   if (!filter) return null;
```

To perform this update, I need to develop some tests as well, to ensure that this change does not negatively impact the library's functionality. If you want to send a PR, containing the update and tests, I would be happy with your contribution. But I will talk to my friend, who maintains the library with me, to see if he can perform this feature.

**Comment by EniotnaTennob** [comment]
Hi @lucasrochagit 
Thank you for your quick reply, I try to post a PR ASAP.
Best regards
